// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/grant-store @ 35afd5fe63b337f5398080965c8df746e60cd3af-dirty
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: grant.go

/**
 * GrantRequest is what a caller sends to create a grant.
 */
export interface GrantRequest {
  principal_id: string;
  relation: string;
  resource_type: string;
  resource_id: string;
  note: string;
}
/**
 * Grant is one relationship tuple.
 */
export interface Grant {
  id: string;
  seq: number /* int64 */;
  principal_id: string;
  relation: string;
  resource_type: string;
  resource_id: string;
  note: string;
  granted_at: number /* int64 */;
  revoked_at: number /* int64 */;
}
/**
 * Counts is the /health summary.
 */
export interface Counts {
  grants: number /* int */;
  active: number /* int */;
  revoked: number /* int */;
  principals: number /* int */; // distinct principals holding an active grant
}

//////////
// source: relation.go

export const RelationCanUse = "can_use";
export const RelationCanRunAs = "can_run_as";
export const RelationCanDispatchOn = "can_dispatch_on";
export const RelationWorksWith = "works_with";
export const RelationCanView = "can_view";
export const RelationCanEdit = "can_edit";
export const RelationCanAdminister = "can_administer";
/**
 * RelationDefinition is everything a caller needs to offer one relation.
 */
export interface RelationDefinition {
  name: string;
  resource_types: string[];
  /**
   * Enforced says llm-bridge-server filters a session's offer by this
   * relation. False means the relation is a list someone reads, not a lock.
   */
  enforced: boolean;
  description: string;
}

//////////
// source: resource_type.go

export const ResourceTypeAgent = "agent";
export const ResourceTypeInstance = "instance";
export const ResourceTypeMachine = "machine";
export const ResourceTypeSkill = "skill";
export const ResourceTypeTool = "tool";
export const ResourceTypeBoard = "board";

//////////
// source: server.go

